### ISSUE TITLE
BUG - po podpise nejde tlacitko STIAHNUT 

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#11]

**Comment by mtruban** [comment]
- treba to namapovat na databazu uradov a ich mailov. ktoru mame.  (ked ju chcete, napiste mne. nech to nedavam public)

**Comment by mtruban** [comment]
v chrome na macu

**Comment by Agoreddah** [comment]
**Root cause**
Chyba je v implementácií onclick eventu stlačidla Stiahnuť. Metóda createDocument, ktorú event volá, sa snaží získať údaje o html elemente canvas s nakresleným podpisom, ktorý sa však ukryl pri vstupe na krok č. 5. 

**Riešenie**
Dokument je už vytvorený a jeho absolútna adresa sa nachádza v elemente iframe#final. Stiahnutie by sa asi malo správať tak, že po kliknutí na tlačidlo Stiahnuť sa pdfko otvorí v novom okne a užívateľ si ho stiahne tam. Na to postačí jednoduchá jQuery metódka:

``` javascript
jQuery('#download-button').on('click', function(e){ 
    e.preventDefault();
    var src = jQuery('#final').attr('src');
    window.open(src);
});
```

**Comment by peterppp** [comment]
ked idem:
Pripravit Ziadost > Odhalseny > Vytvorit Nahlad > Podpis
a podpisem sa tak mi to zhodi cely prehliadac (iPhone 4S Safari na iOS7)

**Comment by s7anley** [comment]
@peterppp vytvor na to ďalšiu issue.

**Comment by marsher** [comment]
Vdaka s7anley za fix, mergujem #34
